
project:
  type: website
  output-dir: docs
  resources: 
    - CNAME
  
website:
  title: "Observatorio de Economía Política"
  site-url: https://www.oepsociologia.ar/
  navbar:
    left:
      - href: index.qmd
        text: Inicio
#      - href: about/index.qmd
#        text: Sobre nosotros
#      - href: notas.qmd
#        text: Notas
#      - href: publicaciones/index.qmd
#        text: Publicaciones
#  search: true

format:
  html:
    theme: cosmo
    css: assets/styles.css
